apiVersion: v1
kind: Service
metadata:
  name: frontend-active
  namespace: production
  labels:
    app: frontend
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /health
spec:
  type: ClusterIP   # NodePort required for ALB Ingress in "instance" target-type mode
  selector:
    app: frontend   # Argo Rollouts patches this selector to point at blue/green ReplicaSet
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP